## OneShot Numpy with Chai aur Code

In [1]:
import numpy as np

### Arrays

In [2]:
arr_1d = np.array([1,2,3,4,5])

In [3]:
arr_2d = np.array([[1, 3, 5], [7, 8, 9]])

In [4]:
print("1D array:\n", arr_1d)
print("2d Array:\n", arr_2d)

1D array:
 [1 2 3 4 5]
2d Array:
 [[1 3 5]
 [7 8 9]]


### List vs Numpy Array


In [5]:
py_list = [1, 2, 3]
print("Python List multiplication:\n", py_list * 2)

Python List multiplication:
 [1, 2, 3, 1, 2, 3]


In [6]:
np_array = np.array([1,3,5])
print("Numpy array:\n", np_array * 2)

Numpy array:
 [ 2  6 10]


In [7]:
import time
start = time.time()
py_list = [i *2  for i in range(10000000)] * 2
print("Time to complete the operation with python list:\n", time.time() - start)

num_start = time.time()
np_array = np.arange(10000000) * 2
print("Time to complete the operation with numpy list:\n", time.time() - num_start)


Time to complete the operation with python list:
 0.9692518711090088
Time to complete the operation with numpy list:
 0.06299901008605957


### Creating arrays with scratch


In [8]:
zeros = np.zeros([3,4])
print(zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [10]:
ones = np.ones([3,3])
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [11]:
full = np.full((2, 2), 8)
print(full)

[[8 8]
 [8 8]]


In [12]:
random = np.random.random([2, 4])
print(random)

[[0.63057599 0.66698537 0.18641457 0.71941796]
 [0.56191575 0.13934511 0.7932133  0.99231189]]


In [13]:
sequence = np.arange(0, 10, 2)
print(sequence)

[0 2 4 6 8]


### Vector, Matrix and Tensor


In [14]:
vector = np.array([1, 2, 4 ,6])
print(vector)

[1 2 4 6]


In [15]:
matrix = np.array([[1, 3, 5], [7, 9, 11]])
print(matrix)

[[ 1  3  5]
 [ 7  9 11]]


In [16]:
tensor = np.array([[[1, 2], [3, 4]], 
                   [[5, 6], [7, 8]]])
print(tensor)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Arrays props

In [17]:
array = np.array([[1, 3, 5], [7, 9, 11]])
print("Shape:\t", array.shape)
print("Dimension:\t", array.ndim)
print("Size:\t", array.size)
print("Dtype:\t", array.dtype)


Shape:	 (2, 3)
Dimension:	 2
Size:	 6
Dtype:	 int64


### Array Reshaping

In [18]:
arr1 = np.arange(12)
print("Original array:\t", arr1)

Original array:	 [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [19]:
reshape = arr1.reshape([3,4])
print(reshape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
flatened = reshape.flatten() #Returs the copy of the array
print(flatened)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
raveled = reshape.ravel() #Actual array
print(raveled)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [22]:
#Transpose
transpose = reshape.T
print(transpose)

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
